name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or whatever your default branch is

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # or specify a build directory like 'dist' or 'build'
      - uses: actions/deploy-pages@v4